# Generated by Django 5.1.7 on 2025-03-15 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_course_created_at_course_students_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='content_page',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='order',
        ),
        migrations.AddField(
            model_name='lesson',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='lesson',
            name='template',
            field=models.CharField(choices=[('template_1.html', 'Diseño 1'), ('template_2.html', 'Diseño 2'), ('template_3.html', 'Diseño 3')], default='template_1.html', max_length=50),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
