# Generated by Django 5.1.7 on 2025-03-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_lesson_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='content_page',
            field=models.TextField(blank=True, null=True),
        ),
    ]
