# Generated by Django 5.1.7 on 2025-04-08 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_lesson_options_lesson_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='template',
        ),
    ]
