# Generated by Django 5.1.7 on 2025-04-10 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_lesson_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
    ]
