# Generated by Django 5.1.7 on 2025-04-11 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_course_image_course_youtube_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='template',
            field=models.CharField(default='course/lessons/curso/leccion1.html', help_text='Ejemplo: course/lessons/curso/leccion1.html', max_length=100),
        ),
    ]
