# Generated by Django 5.1.7 on 2025-04-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_alter_lesson_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='clientes/logos/')),
                ('pais', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
    ]
