# Generated by Django 5.1.7 on 2025-05-01 16:28

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=course.models.lesson_attachment_path),
        ),
    ]
