# Generated by Django 5.1.7 on 2025-05-01 18:42

import course.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_lesson_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='attachment',
        ),
        migrations.CreateModel(
            name='ArchivoAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=course.models.lesson_attachment_path)),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='course.lesson')),
            ],
        ),
    ]
